name: renv-python
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2024.2.2
  - libcxx=16.0.6
  - libffi=3.4.2
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - perl=5.32.1
  - pip=24.0
  - python=3.7.12
  - python_abi=3.7
  - readline=8.2
  - setuptools=69.0.3
  - sqlite=3.45.3
  - tk=8.6.13
  - viennarna=2.5.1
  - wheel=0.42.0
  - xz=5.2.6
